require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnimesController do

  # This should return the minimal set of attributes required to create a valid
  # Anime. As you add validations to Anime, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnimesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all animes as @animes" do
      anime = Anime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:animes).should eq([anime])
    end
  end

  describe "GET show" do
    it "assigns the requested anime as @anime" do
      anime = Anime.create! valid_attributes
      get :show, {:id => anime.to_param}, valid_session
      assigns(:anime).should eq(anime)
    end
  end

  describe "GET new" do
    it "assigns a new anime as @anime" do
      get :new, {}, valid_session
      assigns(:anime).should be_a_new(Anime)
    end
  end

  describe "GET edit" do
    it "assigns the requested anime as @anime" do
      anime = Anime.create! valid_attributes
      get :edit, {:id => anime.to_param}, valid_session
      assigns(:anime).should eq(anime)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Anime" do
        expect {
          post :create, {:anime => valid_attributes}, valid_session
        }.to change(Anime, :count).by(1)
      end

      it "assigns a newly created anime as @anime" do
        post :create, {:anime => valid_attributes}, valid_session
        assigns(:anime).should be_a(Anime)
        assigns(:anime).should be_persisted
      end

      it "redirects to the created anime" do
        post :create, {:anime => valid_attributes}, valid_session
        response.should redirect_to(Anime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved anime as @anime" do
        # Trigger the behavior that occurs when invalid params are submitted
        Anime.any_instance.stub(:save).and_return(false)
        post :create, {:anime => {}}, valid_session
        assigns(:anime).should be_a_new(Anime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Anime.any_instance.stub(:save).and_return(false)
        post :create, {:anime => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested anime" do
        anime = Anime.create! valid_attributes
        # Assuming there are no other animes in the database, this
        # specifies that the Anime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Anime.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => anime.to_param, :anime => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested anime as @anime" do
        anime = Anime.create! valid_attributes
        put :update, {:id => anime.to_param, :anime => valid_attributes}, valid_session
        assigns(:anime).should eq(anime)
      end

      it "redirects to the anime" do
        anime = Anime.create! valid_attributes
        put :update, {:id => anime.to_param, :anime => valid_attributes}, valid_session
        response.should redirect_to(anime)
      end
    end

    describe "with invalid params" do
      it "assigns the anime as @anime" do
        anime = Anime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Anime.any_instance.stub(:save).and_return(false)
        put :update, {:id => anime.to_param, :anime => {}}, valid_session
        assigns(:anime).should eq(anime)
      end

      it "re-renders the 'edit' template" do
        anime = Anime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Anime.any_instance.stub(:save).and_return(false)
        put :update, {:id => anime.to_param, :anime => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested anime" do
      anime = Anime.create! valid_attributes
      expect {
        delete :destroy, {:id => anime.to_param}, valid_session
      }.to change(Anime, :count).by(-1)
    end

    it "redirects to the animes list" do
      anime = Anime.create! valid_attributes
      delete :destroy, {:id => anime.to_param}, valid_session
      response.should redirect_to(animes_url)
    end
  end

end
